### ISSUE TITLE
crash when opening network drive in terminal

### ISSUE THREAD

**Issue by acscd** [mate-desktop-legacy-archive/mate-file-manager-open-terminal#8] opened 2013-09-04 00:34 UTC
I'm not sure whether to report this here or under mate-file-manager, but I'll try here.

Whenever I have a network drive mounted and I right click on or in it and select open in terminal, caja crashes. I'm using MATE 1.6.1, on Sabayon x86_64.

**Comment by raveit65** [comment] 2013-09-14 12:20
Can you open a terminal in 'sftp://localhost/' for confirming?
This crashed in my fedora box too.

**Comment by stefano-k** [comment] 2013-09-26 08:41
@NiceandGently do you have a backtrace?

**Comment by raveit65** [comment] 2013-09-26 09:49
@stefano-k 
I think this is the same issue. backtrace (fedora report) and possible solution.
https://github.com/mate-desktop/mate-file-manager-open-terminal/issues/9

**Comment by stefano-k** [comment] 2013-09-26 09:50
Duplicate of #9

**Closed as completed by stefano-k** 2013-09-26 09:50 UTC
